# Generated by Django 5.2.8 on 2025-11-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comerciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=150, verbose_name='Nombre y Apellido completo')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico (Único)')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Número de WhatsApp')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Hash de Contraseña')),
                ('relacion_negocio', models.CharField(choices=[('DUENO', 'Dueño/a'), ('CONYUGE', 'Cónyuge'), ('HIJO', 'Hijo/a'), ('TRABAJADOR', 'Trabajador/a'), ('OTRO_RELACION', 'Otro')], max_length=50, verbose_name='Relación con el Negocio')),
                ('tipo_negocio', models.CharField(choices=[('ALMACEN', 'Almacén'), ('BOTILLERIA', 'Botillería'), ('CARNICERIA', 'Carnicería'), ('COMIDA_RAPIDA', 'Comida rápida'), ('FERIA_LIBRE', 'Feria libre'), ('FERRETERIA', 'Ferretería'), ('FRUTERIA', 'Frutería y Verdulería'), ('OTRO_NEGOCIO', 'Otro')], max_length=50, verbose_name='Tipo de Negocio')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna de Ubicación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexión')),
            ],
            options={
                'verbose_name': 'Comerciante',
                'verbose_name_plural': 'Comerciantes',
            },
        ),
    ]
