# Generated by Django 5.2.5 on 2025-11-13 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Publicación')),
                ('contenido', models.TextField(verbose_name='Contenido del Post')),
                ('categoria', models.CharField(choices=[('DUDA', 'Duda / Pregunta'), ('OPINION', 'Opinión / Debate'), ('RECOMENDACION', 'Recomendación'), ('NOTICIA', 'Noticia del Sector'), ('GENERAL', 'General')], default='GENERAL', max_length=50, verbose_name='Categoría')),
                ('imagen_url', models.URLField(blank=True, null=True, verbose_name='URL de Imagen/Link')),
                ('etiquetas', models.CharField(blank=True, max_length=255, verbose_name='Etiquetas (@usuarios, hashtags)')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='usuarios.comerciante', verbose_name='Comerciante')),
            ],
            options={
                'verbose_name': 'Publicación de Foro',
                'verbose_name_plural': 'Publicaciones de Foro',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
