# Generated by Django 5.2.5 on 2025-11-18 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_beneficio_imagen_url_remove_beneficio_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='proveedores/fotos/')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_contacto', models.CharField(blank=True, help_text='Formato: +569XXXXXXXX', max_length=12, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='nivel_actual',
            field=models.CharField(choices=[('BRONCE', 'Bronce'), ('PLATA', 'Plata'), ('ORO', 'Oro'), ('PLATINO', 'Platino'), ('DIAMANTE', 'Diamante')], default='BRONCE', max_length=50, verbose_name='Nivel de Beneficios'),
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('rubros_ofertados', models.CharField(help_text='Separados por coma', max_length=255, verbose_name='Rubros Ofertados')),
                ('zona_geografica', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='usuarios.proveedor')),
            ],
            options={
                'verbose_name': 'Propuesta de Proveedor',
                'verbose_name_plural': 'Propuestas de Proveedores',
            },
        ),
    ]
