# Generated by Django 5.2.5 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_proveedor_alter_comerciante_nivel_actual_propuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comerciante',
            name='es_proveedor',
            field=models.BooleanField(default=False, verbose_name='Es Proveedor'),
        ),
    ]
