# Generated by Django 5.2.5 on 2025-11-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_comerciante_es_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comerciante',
            name='tipo_negocio',
            field=models.CharField(choices=[('ALMACEN', 'Almacén de Barrio'), ('MINIMARKET', 'Minimarket'), ('BOTILLERIA', 'Botillería'), ('PANADERIA', 'Panadería/Pastelería'), ('FERIA', 'Feria Libre'), ('KIOSCO', 'Kiosco'), ('FOODTRUCK', 'Food Truck/Carro de Comida'), ('PELUQUERIA', 'Peluquería / Barbería'), ('FARMACIA', 'Farmacia / Botica'), ('LAVANDERIA', 'Lavandería'), ('LIBRERIA', 'Librería / Papelería'), ('REPARACION', 'Reparación de Calzado/Ropa'), ('FLORERIA', 'Florería'), ('TECNOLOGIA_ACC', 'Tecnología / Accesorios'), ('MASCOTAS', 'Productos para Mascotas'), ('COMIDA_RAPIDA', 'Comida Rápida (Local/Delivery)'), ('ARTESANIA', 'Artesanía / Regalos'), ('FERRETERIA', 'Ferretería'), ('VERDULERIA', 'Verdulería / Frutería'), ('JUGUETERIA', 'Juguetería'), ('VESTUARIO', 'Vestuario / Ropa Usada')], max_length=20),
        ),
    ]
