# Generated by Django 5.2.5 on 2025-11-20 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_comerciante_tipo_negocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Título o nombre de la notificación.', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción o cuerpo del mensaje.')),
                ('remitente', models.CharField(blank=True, help_text='Quién generó la notificación (e.g., Admin, Foro, Proveedor).', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('leido', models.BooleanField(default=False)),
                ('enlace_url', models.URLField(blank=True, null=True)),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.comerciante')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
